// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHKXnvl6zrSoeJJKPr6H5IDEJ_hf-PE0',
    appId: '1:61654628298:web:b8e85b5c8948a82fbc4133',
    messagingSenderId: '61654628298',
    projectId: 'mvpfirebase-fb103',
    authDomain: 'mvpfirebase-fb103.firebaseapp.com',
    storageBucket: 'mvpfirebase-fb103.appspot.com',
    measurementId: 'G-CB87D2G290',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbud4hyqbJMhf3bD_bfEVgLFYu--xj9A',
    appId: '1:61654628298:android:3704005996952aa9bc4133',
    messagingSenderId: '61654628298',
    projectId: 'mvpfirebase-fb103',
    storageBucket: 'mvpfirebase-fb103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrNdqxaKvNBnmeiRUh5LVRBipBEnMoyEM',
    appId: '1:61654628298:ios:1793737f104fa552bc4133',
    messagingSenderId: '61654628298',
    projectId: 'mvpfirebase-fb103',
    storageBucket: 'mvpfirebase-fb103.appspot.com',
    iosBundleId: 'com.example.mvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrNdqxaKvNBnmeiRUh5LVRBipBEnMoyEM',
    appId: '1:61654628298:ios:5cded7f8a172d4b1bc4133',
    messagingSenderId: '61654628298',
    projectId: 'mvpfirebase-fb103',
    storageBucket: 'mvpfirebase-fb103.appspot.com',
    iosBundleId: 'com.example.mvp.RunnerTests',
  );
}
